# Sample .travis.yml for R projects

language: r
warnings_are_errors: false
sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

bioc_packages:
  - BSgenome
  - GenomicRanges
  - Biostrings

r_github_packages:
  - jimhester/covr
  - BushmanLab/intSiteRetriever

after_success:
  - Rscript -e 'library(covr);codecov()'
